[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686f9a"
blue = "#00a3cc"
cyan = "#7a5ccc"
green = "#5ccc96"
magenta = "#f2ce00"
red = "#e33400"
white = "#f0f1ce"
yellow = "#b3a1e6"

[colors.normal]
black = "#000000"
blue = "#00a3cc"
cyan = "#7a5ccc"
green = "#5ccc96"
magenta = "#f2ce00"
red = "#e33400"
white = "#686f9a"
yellow = "#b3a1e6"

[colors.primary]
background = "#0f111b"
foreground = "#ecf0c1"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11

[font.bold]
family = "Noto Sans Mono"
style = "Medium"

[font.glyph_offset]

x = -1
y = 0

[font.italic]
family = "Noto Sans Mono"
style = "Italic"

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[font.offset]
x = -1
y = 1

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.9
